Developer ergonomics.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -1,11 +1,53 @@
 version: '3'
 output: prefixed
+env:
+  NPM_CONFIG_AUDIT: "false"
+  NPM_CONFIG_FUND: "false"
+  NPM_CONFIG_UPDATE_NOTIFIER: "false"
+
+  # The OAuth Client Credentials Client ID for handling Google signins on this application.
+  NEXT_PUBLIC_XNGIN_GOOGLE_CLIENT_ID: 222213100775-qa1ajcrk48il70itcbdcvgr9ib5t08uf.apps.googleusercontent.com
+  # The base URL of the xngin API server. Code will append the paths to the API endpoints (e.g. v1/m/apikeys, filters).
+  NEXT_PUBLIC_XNGIN_API_BASE_URL: http://localhost:8000
+  # The base URL of the xngin OIDC API.
+  NEXT_PUBLIC_XNGIN_OIDC_BASE_URL: http://localhost:8000/v1/a/oidc
+  # The URL that Google will redirect the user to when authentication is complete. This should be the public-facing URL
+  # of the SPA and also should be set as a valid redirect URI in the Google Cloud config for this OAuth Client.
+  NEXT_PUBLIC_XNGIN_OIDC_REDIRECT_URI: http://localhost:3000/
 tasks:
-  update-api-spec: |
-    curl --max-time 3 -o /tmp/apispec.json http://localhost:8000/openapi.json
-    jq . /tmp/apispec.json > openapi.json
-    npx orval --config orval.config.ts
-  lint: npx next lint
-  build: npm run build
-  railway-build: docker build -t xngin-dash -f Dockerfile.railway .
-  railway-run: docker run --rm -it -p 3000:3000 xngin-dash
+  nodedeps:
+    cmd: |            
+      CURRENT_NODE_VERSION=$(node --version | sed 's/v//')    
+      REQUIRED_NODE_VERSION=$(cat .nvmrc)            
+      if [ "$CURRENT_NODE_VERSION" != "$REQUIRED_NODE_VERSION" ]; then
+        echo "Error: node --version of $CURRENT_NODE_VERSION does not match required version $REQUIRED_NODE_VERSION from .nvmrc"
+        echo "Tip: Use 'nvm use' to switch to the correct version"
+        exit 1
+      fi
+      npm install
+  start:
+    desc: "Starts the development server"
+    interactive: true
+    deps:
+      - nodedeps
+    cmd: |      
+      npm run dev
+  genapiclient:
+    desc: "Updates the generated API client from the apiserver running at http://localhost:8000"
+    cmd: |
+      curl --max-time 3 -o /tmp/apispec.json http://localhost:8000/openapi.json
+      jq . /tmp/apispec.json > openapi.json
+      npx orval --config orval.config.ts
+  lint:
+    desc: "Runs the NextJS-managed linter"
+    cmd: npx next lint
+  build:
+    desc: "Production build of the NextJS application"
+    cmd: npm run build
+  railway-build:
+    desc: "Builds the Docker image used by the Railway deployment."
+    cmd: docker build -t xngin-dash -f Dockerfile.railway .
+  railway-run:
+    desc: "Runs the Docker image in a similar way to how Railway runs it."
+    interactive: true
+    cmd: docker run --rm -it -p 3000:3000 xngin-dash
